import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("https://protocolsbyjames.com"),
  title: {
    default: "Protocols by James | Physique & Self-Optimization Coaching",
    template: "%s | Protocols by James",
  },
  description:
    "Personalized coaching system for physique, confidence, and performance. Custom training, nutrition, and lifestyle protocols built for your goals.",
  keywords: [
    "online fitness coaching",
    "physique coach",
    "personal training",
    "nutrition coaching",
    "body recomposition",
    "protocols by james",
  ],
  authors: [{ name: "James Quilter" }],
  creator: "James Quilter",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://protocolsbyjames.com",
    title: "Protocols by James | Physique & Self-Optimization Coaching",
    description:
      "Personalized coaching system for physique, confidence, and performance. Custom training, nutrition, and lifestyle protocols built for your goals.",
    siteName: "Protocols by James",
    // OG image is auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Protocols by James",
    description:
      "Personalized coaching system for physique, confidence, and performance.",
    // Twitter image auto-generated by same file convention
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://protocolsbyjames.com",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
